### ISSUE TITLE
Message Loop

### ISSUE THREAD

**Issue by kirabin** [kirabin/ft_irc#1]
<img width="925" alt="image" src="https://user-images.githubusercontent.com/59910852/130318155-e9fd2be6-3ec1-4cad-b3d3-e4d6b53b4880.png">

**Comment by kirabin** [comment]
You could recreate this problem by making to connections to server and then forcibly closing connection of one of them using signal (ctrl + C)

**Comment by denisnadey** [comment]
Ok fixed
